### PR TITLE
fix styling file name to make it importable by apps

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Fixes issue #17

### CODE REVIEW

**Comment by zigahertz** [comment]
@BryanCrotaz thanks for looking at this. Unfortunately, your change breaks the test suite - we need that `addon.scss` file apparently, at least with the current configuration. I've thought about including this library - https://github.com/ebryn/ember-component-css, maybe that would provide a solution?

**Comment by BryanCrotaz** [comment]
Argh - fixes the app but breaks the tests... hmm. That's a nice addon! I'll take a quick look.

This change is the currently recommended way to do scss in an addon, so it might be the test suite at fault.

**Comment by BryanCrotaz** [comment]
I think I found the problem - testing locally

**Comment by BryanCrotaz** [comment]
:tada:

**Comment by BryanCrotaz** [comment]
Works in my app too

**Comment by zigahertz** [comment]
@BryanCrotaz this looks good - merging now, and I'll bump the version

**Pull request merged**
